### ISSUE TITLE
PreProcessMousePosition should be able to edit an existing Pos.mat file

### ISSUE THREAD

**Issue by SharpWave** [SharpWave/PlacefieldAnalysis#2]

**Comment by nkinsky** [comment]
True.  Currently, you can do this easily by just loading up
Pos_temp.mat. However, the problem with that is that at the end of Pos.mat
it takes all the data, filters it, and then interpolates it...so, to keep
this functionality we will want to keep the raw, unfiltered,
non-interpolated data around in Pos.mat (all the stuff saved in
Pos_temp.mat) currently.
